### ISSUE TITLE
豆瓣的api无法申请

### ISSUE THREAD

**Issue by TH226** [windlany/vue-douban#1]
你好，我按照您的代码实现这个电影的功能，现在做到加载电影这一块，发现加载不出来电影，我想可能是需要申请豆瓣的api才可以，可是我到豆瓣官网，发现豆瓣已经关闭了个人的申请入口，想问下您该怎么办

**Comment by yemaoteng** [comment]
您好～

豆瓣这个项目，是我是从别的地方fork下来的，原地址https://github.com/windlany/vue-douban

目前自己还没有研究过，无法解答您的问题，抱歉。可以尝试联系一下原作者，谢谢～

在 2018年4月24日 上午11:20，hewie <notifications@github.com>写道：

**Comment by windlany** [comment]
因为跨域的原因？我是用node写了一个代理服务器解决跨域，你可以试试。

**Comment by yemaoteng** [comment]
谢谢LAN提醒~回头我也试一试【抱拳】

2018-04-27 16:47 GMT+08:00 LAN <notifications@github.com>:
